Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  LogSavePath: storage/log
  LogFileName: app
  LogFileExt: .log

Database:
  DBType: mysql
  Username: root
  Password: root
  Host: 0.0.0.0:3306
  DBName: db_lianjia
  TablePrefix: lj_
  Charset: utf8
  ParseTime: true
  MaxIdleConns: 10
  MaxOpenConns: 10